### ISSUE TITLE
GRASS hydrologie

### ISSUE THREAD

**Issue by landam** [lfurtkevicova/internship#10]
http://training.gismentors.eu/grass-gis-pokrocily/hydrologie/index.html

**Comment by lfurtkevicova** [comment]
metóda SCS CN aj priemerná dlhodobá strata pôdy - obe časti nanovo podrobne opísané v branch "hydrologie2", viď. [scs-cn.rst a usle.rst](https://github.com/GISMentors/grass-gis-pokrocily/tree/master/hydrologie)

**Comment by lfurtkevicova** [comment]
potrebné prejsť postup aj dáta s K143 !

**Comment by landam** [comment]
muzu domluvit kratkou schuzku kolem 13.30 primo na K143, vyhovuje?

**Comment by lfurtkevicova** [comment]
Prednedávnom som odišla z Dejvíc, keďže si písal, že UZPD nie je. Môžeme zajtra? Dík .. btw môžeme im to aspoň preposlať .. v akom je to stave, čo ty na to?

**Comment by landam** [comment]
mirne jsem upravil (zalomeni na 80 znaku, opravil drobnosti), online na http://geo102.fsv.cvut.cz/~landa/tmp/grass-gis-pokrocily/_build/html/hydrologie/scs-cn.html

**Comment by lfurtkevicova** [comment]
Ahoj, fajn. Ja som na tom odvtedy nerobila a o tých inštrukciách viem len
od víkendu. Pracovala som skôr na QGISe.
Tú hydrológiu považujem zatiaľ za nejaký nástrel .. vďaka

2015-11-16 13:08 GMT+01:00 Martin Landa notifications@github.com:

**Comment by lfurtkevicova** [comment]
Ahoj,

V službe Gmail na webe používam vlastný motív a myslím si, že by sa vám
mohol tiež páčiť.

Vyskúšajte si ho v počítači alebo laptope.

https://mail.google.com/mail/?tm=1#settings/themes/customlight?https%3A%2F%2Flh5.googleusercontent.com%2F-c9W77O0PuoM%2FVHXLRWPSH1I%2FAAAAAAAAAKY%2FmWRfhwJbJWA%2Fs0%2FCimen-ve-Gokyuzu.jpg
