### ISSUE TITLE
upravit data pro stredni evropu v gis.labu

### ISSUE THREAD

**Issue by landam** [lfurtkevicova/internship#19]
viz https://github.com/imincik/gis-lab/issues/354

**Comment by lfurtkevicova** [comment]
Dáta upravené použitím Spatialite GUI. Ich opis dostupný [TU](https://github.com/lfurtkevicova/gis-lab-doc/blob/master/source/docs/other/data.rst).

Pôvodnú databázu som pre istotu nechala. Aj tak nemám prístup do imincik/gis-lab, preto som ju nahrala zatiaľ [TU](https://github.com/lfurtkevicova/gis-lab-doc/blob/master/source/docs/other/natural-earth-new.sqlite). 

Nový projekt  _central-europe-qgis2.8.qgs_ som nevytvárala, používam qgis2.12, aktualizujem to v škole pod gis.lab-om.
